version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: zintranet
          MYSQL_USER: zintranet
          MYSQL_PASSWORD: zintranet
      - image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: zintranet
          MYSQL_USER: zintranet
          MYSQL_PASSWORD: zintranet
    steps:
      - checkout
      - run:
          command: npm ci
          working_directory: backend
      - run:
          command: npm run lint
          working_directory: backend
      - run:
          command: npm run migrate
          working_directory: backend
      - run:
          command: npm test
          working_directory: backend

workflows:
  build:
    jobs:
      - build
