version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: zintranet
          MYSQL_USER: zintranet
          MYSQL_PASSWORD: zintranet
      - image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: zintranet
          MYSQL_USER: zintranet
          MYSQL_PASSWORD: zintranet
    working_directory: backend
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test

workflows:
  build:
    jobs:
      - build
